name: Build and Push

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup.NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Mod
        run: dotnet build --configuration Release --framework net6.0 --no-restore  

      - name: Pack Mod (Optional, but recommended)
        run: dotnet pack --configuration Release --framework net6.0 -o./nupkg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ItemExtensions
          path: |
            bin/Release/net6.0/**/*.dll
            bin/Release/net6.0/**/*.pdb
            bin/Release/net6.0/**/*.json
