name: Build and Push Stardew Valley Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Mod
        run: dotnet build --configuration Release --framework net8.0 --no-restore

      - name: Upload Compiled Mod
        uses: actions/upload-artifact@v4
        with:
          name: ItemExtensions
          path: |
            bin/Release/net6.0/**/*.dll
            bin/Release/net6.0/**/*.pdb
            bin/Release/net6.0/**/*.json

      - name: Prepare Files for Commit
        run: |
          mkdir -p mod_build
          cp -r bin/Release/net6.0/*.dll mod_build/
          cp -r bin/Release/net6.0/*.pdb mod_build/
          cp -r bin/Release/net6.0/*.json mod_build/

      - name: Commit and Push Built Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b built-mod || git checkout built-mod
          cp -r mod_build/* .
          git add *.dll *.pdb *.json
          git commit -m "Auto-commit built mod files"
          git push origin built-mod --force
