name: Build and Push ItemExtensions Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore Dependencies
        run: dotnet restore ItemExtensions.csproj

      - name: Build Mod
        run: dotnet build --configuration Release --framework net8.0 --no-restore

      - name: Publish Mod
        run: dotnet publish --configuration Release --framework net8.0 --output ./bin/Release/net8.0/publish --no-restore

      - name: List published directory for debugging
        run: ls -R ./bin/Release/net8.0/publish/

      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ItemExtensions_Mod_DLL
          path: ./bin/Release/net8.0/publish/ItemExtensions.dll
