name: Build and Push DLLs

on:
  push:
    tags:
      - "v*"  # Runs when you push a tag like v1.0.0
  workflow_dispatch:  # Allows manual triggering in GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Framework
        run: dotnet build --configuration Release --no-restore

      - name: Prepare DLLs for Commit
        run: |
          mkdir -p dlls
          cp bin/Release/net8.0/*.dll dlls/
      
      - name: Commit and Push DLLs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b dll || git checkout dll
          cp -r dlls/* .
          git add *.dll
          git commit -m "Auto-commit built DLLs"
          git push origin dll
